import type {
  Abono,
  Atencion,
  Box,
  Cliente,
  EmpresaFlota,
  Promocion,
  Reportes,
  Reserva,
  Servicio,
  User,
  Vehiculo,
} from "./types";

export const users: (User & { password: string })[] = [
  {
    id: "u1",
    nombre: "Tomás Herrera",
    email: "operador@lavapp.com",
    rol: "OPERADOR",
    lavaderoId: 1,
    password: "operador",
  },
  {
    id: "u2",
    nombre: "Carolina Avellaneda",
    email: "dueno@lavapp.com",
    rol: "DUENO",
    lavaderoId: 1,
    password: "dueno",
  },
  {
    id: "u3",
    nombre: "Clínica Sur",
    email: "flota@lavapp.com",
    rol: "FLOTA",
    password: "flota",
  },
];

export const clientes: Cliente[] = [
  {
    id: "c1",
    nombre: "Lucía",
    apellido: "Gómez",
    telefono: "11 5555-2018",
    email: "lucia.gomez@mail.com",
    fechaRegistro: "2025-03-12",
    fechaUltimaVisita: "2026-05-20",
    frecuente: true,
    inactivo: false,
  },
  {
    id: "c2",
    nombre: "Martín",
    apellido: "Pérez",
    telefono: "11 4444-1188",
    email: "martin.perez@mail.com",
    fechaRegistro: "2024-11-02",
    fechaUltimaVisita: "2026-05-20",
    frecuente: true,
    inactivo: false,
  },
  {
    id: "c3",
    nombre: "Sofía",
    apellido: "Díaz",
    telefono: "11 4788-3344",
    email: "sofia.diaz@mail.com",
    fechaRegistro: "2025-08-19",
    fechaUltimaVisita: "2026-04-01",
    frecuente: false,
    inactivo: true,
  },
  {
    id: "c4",
    nombre: "Juan",
    apellido: "Rivas",
    telefono: "11 4000-9090",
    email: "juan.rivas@mail.com",
    fechaRegistro: "2026-01-08",
    fechaUltimaVisita: "2026-05-20",
    frecuente: false,
    inactivo: false,
  },
  {
    id: "c5",
    nombre: "Ana",
    apellido: "López",
    telefono: "11 4222-1100",
    email: "ana.lopez@mail.com",
    fechaRegistro: "2025-06-14",
    fechaUltimaVisita: "2026-05-19",
    frecuente: true,
    inactivo: false,
  },
  {
    id: "c6",
    nombre: "Clínica Sur",
    apellido: "Flota",
    telefono: "11 4000-7000",
    email: "flota@clinicasur.com",
    fechaRegistro: "2025-02-01",
    fechaUltimaVisita: "2026-05-20",
    frecuente: true,
    inactivo: false,
  },
];

export const vehiculos: Vehiculo[] = [
  {
    id: "v1",
    patente: "AB 123 CD",
    marca: "Peugeot",
    modelo: "208",
    tipo: "Auto",
    clienteId: "c1",
    color: "#7C8CFF",
  },
  {
    id: "v2",
    patente: "AC 456 EF",
    marca: "Ford",
    modelo: "Ranger",
    tipo: "Pickup",
    clienteId: "c2",
    color: "#5B6B8C",
  },
  {
    id: "v3",
    patente: "AD 789 GH",
    marca: "Toyota",
    modelo: "Corolla",
    tipo: "Auto",
    clienteId: "c3",
    color: "#C9D2DE",
  },
  {
    id: "v4",
    patente: "AE 321 JK",
    marca: "Volkswagen",
    modelo: "T-Cross",
    tipo: "SUV",
    clienteId: "c4",
    color: "#2A3348",
  },
  {
    id: "v5",
    patente: "AF 654 LM",
    marca: "Chevrolet",
    modelo: "Onix",
    tipo: "Auto",
    clienteId: "c5",
    color: "#E85D4C",
  },
  {
    id: "v6",
    patente: "AG 987 NP",
    marca: "Fiat",
    modelo: "Cronos",
    tipo: "Auto",
    clienteId: "c2",
    color: "#F2F4F8",
  },
  {
    id: "v7",
    patente: "AH 111 QR",
    marca: "Renault",
    modelo: "Kangoo",
    tipo: "Camioneta",
    clienteId: "c6",
    color: "#FFFFFF",
  },
  {
    id: "v8",
    patente: "AI 222 ST",
    marca: "Ford",
    modelo: "Transit",
    tipo: "Camioneta",
    clienteId: "c6",
    color: "#D7DEEA",
  },
];

export const servicios: Servicio[] = [
  {
    id: "s1",
    nombre: "Lavado exterior",
    descripcion: "Lavado de carrocería, ruedas y secado.",
    precio: 8500,
    duracionMin: 25,
  },
  {
    id: "s2",
    nombre: "Lavado completo",
    descripcion: "Exterior + interior básico.",
    precio: 14500,
    duracionMin: 45,
  },
  {
    id: "s3",
    nombre: "Limpieza interior",
    descripcion: "Aspirado, plásticos y vidrios interiores.",
    precio: 9000,
    duracionMin: 35,
  },
  {
    id: "s4",
    nombre: "Detailing",
    descripcion: "Tratamiento premium de interior y exterior.",
    precio: 32000,
    duracionMin: 90,
  },
];

export const boxes: Box[] = [
  { id: "b1", nombre: "Puesto 1", numero: 1, estado: "OCUPADO", atencionId: "a2" },
  { id: "b2", nombre: "Puesto 2", numero: 2, estado: "OCUPADO", atencionId: "a3" },
  { id: "b3", nombre: "Puesto 3", numero: 3, estado: "OCUPADO", atencionId: "a4" },
  { id: "b4", nombre: "Puesto 4", numero: 4, estado: "DISPONIBLE" },
  { id: "b5", nombre: "Puesto 5", numero: 5, estado: "DISPONIBLE" },
  { id: "b6", nombre: "Puesto 6", numero: 6, estado: "DISPONIBLE" },
  { id: "b7", nombre: "Puesto 7", numero: 7, estado: "DISPONIBLE" },
  { id: "b8", nombre: "Puesto 8", numero: 8, estado: "DISPONIBLE" },
];

export const atenciones: Atencion[] = [
  {
    id: "a1",
    vehiculoId: "v1",
    clienteId: "c1",
    servicioIds: ["s2"],
    fechaIngreso: "2026-05-20T09:10:00",
    horaEstimadaInicio: "2026-05-20T09:40:00",
    horaEstimadaFin: "2026-05-20T10:25:00",
    estado: "EN_ESPERA",
    demoraMin: 0,
    origen: "WALK_IN",
    tokenSeguimiento: "LUC208",
    fotos: [],
  },
  {
    id: "a2",
    vehiculoId: "v2",
    clienteId: "c2",
    servicioIds: ["s4"],
    boxId: "b1",
    fechaIngreso: "2026-05-20T08:30:00",
    horaEstimadaInicio: "2026-05-20T08:35:00",
    horaEstimadaFin: "2026-05-20T10:05:00",
    estado: "LAVADO",
    demoraMin: 8,
    origen: "RESERVA",
    tokenSeguimiento: "MAR456",
    fotos: [],
  },
  {
    id: "a3",
    vehiculoId: "v4",
    clienteId: "c4",
    servicioIds: ["s2"],
    boxId: "b2",
    fechaIngreso: "2026-05-20T08:50:00",
    horaEstimadaInicio: "2026-05-20T08:55:00",
    horaEstimadaFin: "2026-05-20T09:40:00",
    estado: "INTERIOR",
    demoraMin: 0,
    origen: "WALK_IN",
    tokenSeguimiento: "JUA321",
    fotos: [],
  },
  {
    id: "a4",
    vehiculoId: "v5",
    clienteId: "c5",
    servicioIds: ["s1"],
    boxId: "b3",
    fechaIngreso: "2026-05-20T09:00:00",
    horaEstimadaInicio: "2026-05-20T09:05:00",
    horaEstimadaFin: "2026-05-20T09:30:00",
    estado: "TERMINACIONES",
    demoraMin: 0,
    origen: "WALK_IN",
    tokenSeguimiento: "ANA654",
    fotos: [],
  },
  {
    id: "a5",
    vehiculoId: "v6",
    clienteId: "c2",
    servicioIds: ["s3"],
    fechaIngreso: "2026-05-20T09:20:00",
    horaEstimadaInicio: "2026-05-20T10:10:00",
    horaEstimadaFin: "2026-05-20T10:45:00",
    estado: "EN_ESPERA",
    demoraMin: 0,
    origen: "WALK_IN",
    tokenSeguimiento: "MAR987",
    fotos: [],
  },
  {
    id: "a6",
    vehiculoId: "v3",
    clienteId: "c3",
    servicioIds: ["s2"],
    fechaIngreso: "2026-05-20T07:50:00",
    horaEstimadaInicio: "2026-05-20T08:00:00",
    horaEstimadaFin: "2026-05-20T08:45:00",
    estado: "LISTO",
    demoraMin: 0,
    origen: "RESERVA",
    tokenSeguimiento: "SOF789",
    fotos: [],
  },
  {
    id: "a7",
    vehiculoId: "v7",
    clienteId: "c6",
    servicioIds: ["s2"],
    fechaIngreso: "2026-05-20T09:05:00",
    horaEstimadaInicio: "2026-05-20T10:30:00",
    horaEstimadaFin: "2026-05-20T11:15:00",
    estado: "EN_ESPERA",
    demoraMin: 0,
    origen: "RESERVA",
    tokenSeguimiento: "FLO111",
    fotos: [],
  },
];

export const reservas: Reserva[] = [
  {
    id: "r1",
    clienteId: "c1",
    vehiculoId: "v1",
    servicioId: "s2",
    fecha: "2026-05-20",
    horario: "11:00",
    estado: "CONFIRMADA",
  },
  {
    id: "r2",
    clienteId: "c5",
    vehiculoId: "v5",
    servicioId: "s1",
    fecha: "2026-05-20",
    horario: "11:30",
    estado: "PENDIENTE",
  },
  {
    id: "r3",
    clienteId: "c2",
    vehiculoId: "v2",
    servicioId: "s4",
    fecha: "2026-05-20",
    horario: "16:00",
    estado: "CONFIRMADA",
  },
  {
    id: "r4",
    clienteId: "c4",
    vehiculoId: "v4",
    servicioId: "s3",
    fecha: "2026-05-21",
    horario: "09:30",
    estado: "LISTA_ESPERA",
  },
  {
    id: "r5",
    clienteId: "c6",
    vehiculoId: "v8",
    servicioId: "s2",
    fecha: "2026-05-20",
    horario: "15:00",
    estado: "CONFIRMADA",
  },
];

export const abonos: Abono[] = [
  {
    id: "ab1",
    clienteId: "c1",
    vehiculoId: "v1",
    tipo: "8 lavados mensuales",
    disponibles: 5,
    utilizados: 3,
    inicio: "2026-05-01",
    vencimiento: "2026-05-31",
  },
  {
    id: "ab2",
    clienteId: "c2",
    vehiculoId: "v2",
    tipo: "4 lavados premium",
    disponibles: 1,
    utilizados: 3,
    inicio: "2026-04-20",
    vencimiento: "2026-05-20",
  },
];

export const promociones: Promocion[] = [
  {
    id: "p1",
    titulo: "20% OFF en el próximo lavado",
    descripcion: "Válido de lunes a jueves hasta el 31/05.",
    vigencia: "2026-05-31",
    activa: true,
  },
  {
    id: "p2",
    titulo: "Beneficio exclusivo",
    descripcion: "Interior bonificado en el 4.º lavado del mes.",
    vigencia: "2026-06-15",
    activa: true,
  },
];

export const flotas: EmpresaFlota[] = [
  {
    id: "f1",
    nombre: "Clínica Sur",
    estado: "Activa",
    vehiculoIds: ["v7", "v8"],
  },
];

export const reportes: Reportes = {
  vehiculosAtendidos: 86,
  tiempoPromedioMin: 18,
  serviciosReagendados: 6,
  ocupacionPromedio: 72,
  vehiculosPorDia: [
    { dia: "Lun", cantidad: 12 },
    { dia: "Mar", cantidad: 16 },
    { dia: "Mié", cantidad: 11 },
    { dia: "Jue", cantidad: 18 },
    { dia: "Vie", cantidad: 14 },
    { dia: "Sáb", cantidad: 10 },
    { dia: "Dom", cantidad: 5 },
  ],
  reservasVsEspontaneos: { reservas: 52, espontaneos: 48 },
  tiempoPorSemana: [
    { dia: "Lun", minutos: 16 },
    { dia: "Mar", minutos: 18 },
    { dia: "Mié", minutos: 15 },
    { dia: "Jue", minutos: 22 },
    { dia: "Vie", minutos: 19 },
    { dia: "Sáb", minutos: 17 },
    { dia: "Dom", minutos: 14 },
  ],
  serviciosMasSolicitados: [
    { servicio: "Lavado completo", cantidad: 32, porcentaje: 37, ingreso: 464000 },
    { servicio: "Lavado exterior", cantidad: 24, porcentaje: 28, ingreso: 204000 },
    { servicio: "Limpieza interior", cantidad: 18, porcentaje: 21, ingreso: 162000 },
    { servicio: "Detailing", cantidad: 12, porcentaje: 14, ingreso: 384000 },
  ],
  insights: [
    {
      tipo: "ok",
      texto: "El jueves concentra el 21% de la demanda. Conveniente reforzar un puesto extra.",
    },
    {
      tipo: "warn",
      texto: "El detailing supera en 12 minutos el tiempo estimado cuando hay más de 3 vehículos en cola.",
    },
    {
      tipo: "info",
      texto: "El 18% de los clientes frecuentes no volvió en 30 días. Hay 2 promociones listas para enviar.",
    },
  ],
};

export const NEXT_STAGE: Record<string, Atencion["estado"] | undefined> = {
  EN_ESPERA: "LAVADO",
  LAVADO: "INTERIOR",
  INTERIOR: "TERMINACIONES",
  TERMINACIONES: "LISTO",
  LISTO: "RETIRADO",
};
